# Generated by Django 6.0.4 on 2026-06-07 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coleccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Pais",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("codigo", models.CharField(max_length=10)),
                (
                    "coleccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paises",
                        to="core.coleccion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Figurita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField()),
                ("nombre", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "coleccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="figuritas",
                        to="core.coleccion",
                    ),
                ),
                (
                    "pais",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="figuritas",
                        to="core.pais",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AlbumUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(default=0)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="albumes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "figurita",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuarios",
                        to="core.figurita",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("usuario", "figurita"),
                        name="album_usuario_figurita_unica",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="pais",
            constraint=models.UniqueConstraint(
                fields=("coleccion", "codigo"), name="pais_unico_por_coleccion_codigo"
            ),
        ),
        migrations.AddConstraint(
            model_name="figurita",
            constraint=models.UniqueConstraint(
                fields=("coleccion", "pais", "numero"),
                name="figurita_unica_por_coleccion_pais_numero",
            ),
        ),
    ]
