# Generated by Django 6.0.4 on 2026-06-07 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MovimientoAlbum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delta", models.IntegerField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("manual", "Carga manual"),
                            ("canje", "Canje"),
                            ("ajuste", "Ajuste"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("descripcion", models.CharField(blank=True, max_length=200)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("sincronizado", models.BooleanField(default=False)),
                (
                    "figurita",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos",
                        to="core.figurita",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos_album",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
